### ISSUE TITLE
Creating a file-log (same for OpenTelemetry plugin resource) plugin at Global Level ends up with a unmarshal error of the response

### ISSUE THREAD

**Issue by andrea-migliaccio** [Kong/terraform-provider-konnect#24]
│ Error: failure to invoke API
│
│   with module.multi_control_planes_dev[0].konnect_gateway_plugin_file_log.file_log_plugin[0],
│   on modules/control-plane/control-plane.tf line 54, in resource "konnect_gateway_plugin_file_log" "file_log_plugin":
│   54: resource "konnect_gateway_plugin_file_log" "file_log_plugin" {
│
│ error unmarshalling json response body: json: cannot unmarshal array into Go value of type map[string]interface {}

```
resource "konnect_gateway_plugin_file_log" "file_log_plugin" {
  config = {
    path = "/dev/stdout"
    reopen = false
  }
  enabled = true
  protocols = ["grpc","grpcs","http","https","udp","ws","wss","tls"]

  control_plane_id = konnect_gateway_control_plane.kcp.id
}
```

It seems that the go class is not aligned with the kong api response schema.. I guess..

**Comment by mheap** [comment]
Thanks for the report @andrea-migliaccio - can you please test `v0.3.0`, which should resolve this issue

**Comment by andrea-migliaccio** [comment]
I'm re-testing everything this afternoon. I'll provide you with a feedback on each issues

Thanks!

**Comment by andrea-migliaccio** [comment]
I'm not getting the error anymore globally for the plugin i provisioned (OpenTelemetry and file-log) and the "propagation" part is also present for OpenTelemetry as reported in the issues #25
