### ISSUE TITLE
Missing example resource

### ISSUE THREAD

**Issue by gordon-writer** [Kong/terraform-provider-konnect#35]
There is no example resource for `gateway_plugin_key_auth` in the `/examples/resources/` dir. I can't remember if there were others I couldn't find.

There _is_ an example for `gateway_key_auth` but note this is a different resource!

Strangely, if you search for [gateway_plugin_key_auth in the repo](https://github.com/search?q=repo%3AKong%2Fterraform-provider-konnect%20gateway_plugin_key_auth&type=code), you can see a `.speakeasy/` file appears to contains paths to where the resource examples should exist.

**Comment by gordon-writer** [comment]
`konnect_gateway_plugin_pre_function` also has the same problem

**Comment by mheap** [comment]
Hey @gordon-writer. All of the plugin examples are missing from the repo while we build out the docs.

In the interim, you can find examples on the Kong docs site: https://docs.konghq.com/hub/kong-inc/acl/how-to/basic-example/?tab=konnect-terraform

All configuration parameters listed in the configuration reference are available https://docs.konghq.com/hub/kong-inc/acl/configuration/
