### ISSUE TITLE
Feature request - konnect_team_role enum of valid values for some properties

### ISSUE THREAD

**Issue by andrea-migliaccio** [Kong/terraform-provider-konnect#39]
It would be beneficial to decorate the following properties of the konnect_team_role with the enum of valid values, if such an enumeration actually exists:

* entity_type_name (eg. Control Plane, etc..)
* role_name (Admin, Plugin Admin, etc)

**Comment by mheap** [comment]
Thanks @andrea-migliaccio. I've requested that this be added to our data source from the team that owns it
