### ISSUE TITLE
Feature Request - Generate Data Plane client certificate

### ISSUE THREAD

**Issue by andrea-migliaccio** [Kong/terraform-provider-konnect#41]
I must admin, I haven't tried to explore the data_plane_client_certificate  resource "internals" but, based on the provided example, it seems that it doesn't support the kong-generated client certificate instead of providing our own.

The idea is basically to reproduce this and then grab the output and store somewhere in our key vault for further uses (eg. automating the data plane's deployment on k8s)

![image](https://github.com/Kong/terraform-provider-konnect/assets/97603234/d5d3d0b7-b0a0-4201-9cb7-c6396e9310fd)

**Comment by mheap** [comment]
@andrea-migliaccio This button generates a certificate on the client to ensure that Konnect never sees your private key. There is no corresponding API endpoint.

To do this in a declarative way, you would use `openssl` (see [these docs](https://docs.konghq.com/konnect/gateway-manager/data-plane-nodes/renew-certificates/?tab=konnect-api#generate-new-data-plane-certificate)) and use the [gateway_data_plane_client_certificate](https://github.com/Kong/terraform-provider-konnect/blob/main/examples/resources/gateway_data_plane_client_certificate.tf) resource to attach the certificate to your control plane

**Comment by andrea-migliaccio** [comment]
That's clear. I'll close this issue then! Thank you @mheap
