### ISSUE TITLE
Remove quoted type constraints

### ISSUE THREAD

**Issue by battlebyte** [Kong/terraform-provider-konnect#82]
Type constraints in quotes was required in Terraform 0.11 and earlier, but that form is now deprecated and will be removed in a future version of Terraform. For example:

```
variable "control_plane_id" {
  type = "string"
  default = "YOUR_CONTROL_PLANE_ID"
}
```

should be 

```
variable "control_plane_id" {
  type = string
  default = "YOUR_CONTROL_PLANE_ID"
}
```

if the quotes are present, an error is shown during `terraform apply`.

**Comment by mheap** [comment]
@battlebyte Where are quoted `type` constraints used in this repo? I'm struggling to find what the action is here

**Comment by battlebyte** [comment]
@mheap sorry, wrong repo 😞 . The real thing is https://github.com/Kong/deck/pull/1412

**Comment by mheap** [comment]
This was resolved in Deck
