### ISSUE TITLE
"konnect_api_product_specification" Resource Fails to Recognize Variable for Name Attribute in Terraform Provider

### ISSUE THREAD

**Issue by putivan** [Kong/terraform-provider-konnect#89]
When using the konnect_api_product_specification resource in the Kong Terraform provider, the name attribute does not accept a variable value. Running terraform plan with the name set to a variable results in the following error:

> ╷
> │ Error: must match the pattern ^.+(?:\.yaml|\.yml|\.json)$
> │ 
> │   with konnect_api_product_specification.demo_base_spec,
> │   on main.tf line 45, in resource "konnect_api_product_specification" "demo_base_spec":
> │   45:   name                   = var.spec_file_name
> │ 
> │ name: The name of the OpenAPI specification to upload
> ╵

However, hardcoding the name attribute (e.g., name = "openapi.yaml") works as expected. Note that the "Terraform console" command successfully reads the value from the variable, so it appears to be an issue specific to this resource.

![image](https://github.com/user-attachments/assets/b0a71639-98b4-462d-9a36-40c99a8afcda)

Sample terraform configuration file: 
[main.tf.txt](https://github.com/user-attachments/files/17463574/main.tf.txt)

**Comment by mheap** [comment]
Thanks @putivan! I think I've worked out the issue and will try to get a release out in the next 10 days or so

**Comment by mheap** [comment]
I've attached a PR that resolves this issue. I plan to release on Monday

**Comment by mheap** [comment]
This is released in 2.0.0

**Comment by putivan** [comment]
Confirmed 2.0.2 fixed the issue! Thank you @mheap
