### ISSUE TITLE
Add Azure to list of supported Cloud Gateway Configuration providers

### ISSUE THREAD

**Issue by baumanzee** [Kong/terraform-provider-konnect#90]
Currently the Cloud Gateway Configuration only supports "AWS" as a provider.  We need to add "Azure" to the list of providers for upcoming support.

https://github.com/Kong/terraform-provider-konnect/blob/7d0b771181e74755b52831d35313e5b06aae22bc/internal/provider/cloudgatewayconfiguration_resource.go#L317-L327

**Comment by mheap** [comment]
Resolved in #96. Should be available next week

**Comment by mheap** [comment]
This is released in 2.0.0
