### ISSUE TITLE
Missing data sources in 1.0 version

### ISSUE THREAD

**Issue by sigismund** [Kong/terraform-provider-konnect#91]
It seems that almost all of data sources were removed in version 1.0. 

If this was done intentionally it would be also nice to mentioned this in changelog. I understand that 0.x is pre-release and stuff can break, but this makes pretty much all of the previous implementations useless without any warning about it.

**Comment by mheap** [comment]
This was done intentionally as we're waiting to solve data providers properly in #10. Keeping the pre-release providers in a 1.0 release would commit us to maintaining them as-is, which isn't something we could do.

Release 0.7.0 is identical to 1.0.0, but with the data sources in place
